"""initial schema with RAG support

Revision ID: 0bf405beec27
Revises: 
Create Date: 2026-08-17 15:30:51.661869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0bf405beec27'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_name', sa.String(length=200), nullable=False),
    sa.Column('org_type', sa.String(length=50), nullable=False),
    sa.Column('admin_location', sa.String(length=300), nullable=True),
    sa.Column('admin_code', sa.String(length=6), nullable=True),
    sa.Column('org_email', sa.String(length=100), nullable=True),
    sa.Column('contact_person', sa.String(length=50), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('org_profile', sa.Text(), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_org_name'), ['org_name'], unique=False)

    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunks_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_source_type'), ['source_type'], unique=False)
        batch_op.create_index('ix_document_source', ['source_type', 'source_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('leader_name', sa.String(length=50), nullable=False),
    sa.Column('leader_contact', sa.String(length=20), nullable=True),
    sa.Column('leader_email', sa.String(length=100), nullable=True),
    sa.Column('student_id', sa.String(length=20), nullable=True),
    sa.Column('university', sa.String(length=100), nullable=True),
    sa.Column('team_specialty', sa.String(length=50), nullable=False),
    sa.Column('team_description', sa.Text(), nullable=True),
    sa.Column('teacher_name', sa.String(length=50), nullable=True),
    sa.Column('teacher_contact', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_team_name'), ['team_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_team_specialty'), ['team_specialty'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('university', sa.String(length=100), nullable=True),
    sa.Column('contact', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_student_id'), ['student_id'], unique=True)

    op.create_table('demands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('internship_location', sa.String(length=300), nullable=True),
    sa.Column('estimated_time', sa.String(length=100), nullable=True),
    sa.Column('requirements_content', sa.Text(), nullable=True),
    sa.Column('target_majors', sa.JSON(), nullable=True),
    sa.Column('org_type', sa.String(length=50), nullable=True),
    sa.Column('org_name', sa.String(length=200), nullable=True),
    sa.Column('contact_info', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demands_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_demands_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_demands_status'), ['status'], unique=False)

    op.create_table('forum_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('author_name', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('team', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_posts_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_posts_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_posts_title'), ['title'], unique=False)

    op.create_table('team_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('member_name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_members_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_user_id'), ['user_id'], unique=False)

    op.create_table('forum_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('author_name', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forum_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_comments_post_id'), ['post_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_comments_post_id'))

    op.drop_table('forum_comments')
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_team_id'))

    op.drop_table('team_members')
    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_posts_title'))
        batch_op.drop_index(batch_op.f('ix_forum_posts_category'))
        batch_op.drop_index(batch_op.f('ix_forum_posts_author_id'))

    op.drop_table('forum_posts')
    with op.batch_alter_table('demands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demands_status'))
        batch_op.drop_index(batch_op.f('ix_demands_company_name'))
        batch_op.drop_index(batch_op.f('ix_demands_company_id'))

    op.drop_table('demands')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_student_id'))

    op.drop_table('users')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_team_specialty'))
        batch_op.drop_index(batch_op.f('ix_teams_team_name'))

    op.drop_table('teams')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index('ix_document_source')
        batch_op.drop_index(batch_op.f('ix_document_chunks_source_type'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_source_id'))

    op.drop_table('document_chunks')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_org_name'))

    op.drop_table('companies')
    # ### end Alembic commands ###
